package ch.uzh.ifi.seal.soprafs15.group_09_android.models.beans;

import android.os.Parcelable;
import android.support.annotation.Nullable;

import java.util.List;

import auto.parcel.AutoParcel;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.LegBettingTile;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.RaceBettingCard;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.gson.AutoGson;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.enums.UserStatus;

@AutoParcel @AutoGson
public abstract class UserBean implements Parcelable {

    // AutoParcel / AutoGson demand abstract dummy methods, getter/setter get autogenerated upon build.
    @Nullable
    public abstract Long id();
    @Nullable
    public abstract Integer playerId();
    @Nullable
    public abstract String username();
    @Nullable
    public abstract Integer age();
    @Nullable
    public abstract String token();
    @Nullable
    public abstract UserStatus status();
    @Nullable
    public abstract String game();
//    public abstract GameBean game();
    @Nullable
    public abstract List<MoveBean> moves();
    @Nullable
    public abstract Integer money();
    @Nullable
    public abstract Integer numberOfMoves();
    @Nullable
    public abstract List<RaceBettingCard> raceBettingCards();
    @Nullable
    public abstract List<LegBettingTile> legBettingTiles();
    @Nullable
    public abstract String channelName();


    public static UserBean create( String username,
                               Integer age) {
        return new AutoParcel_UserBean( null, null, username, age, null,
                                    null, null, null, null,
                                    null, null, null, null);
    }

    public static UserBean setToken( String token ) {
        return new AutoParcel_UserBean( null, null, null, null, token,
                null, null, null, null,
                null, null, null, null);
    }
}

