package ch.uzh.ifi.seal.soprafs15.group_09_android.models;

import android.os.Parcelable;

import com.google.android.gms.auth.GoogleAuthUtil;

import auto.parcel.AutoParcel;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.gson.AutoGson;

@AutoParcel @AutoGson
public abstract class Game implements Parcelable {

    // AutoParcel / AutoGson demand abstract dummy methods, getter/setter get autogenerated upon build.
    public abstract String game();
    // public abstract String owner();

    /**
     * Creates a JSON file from the Game object
     *
     * @param game The name of the game
     * @return JSON file of Game
     */
    /* TODO we need to send also the user token so that the server can identify the current user */
    public static Game create(String game) {
        return new AutoParcel_Game(game);
    }

}

