package ch.uzh.ifi.seal.soprafs15.group_09_android.models;

import android.os.Parcelable;
import android.support.annotation.Nullable;

import auto.parcel.AutoParcel;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.gson.AutoGson;
import ch.uzh.ifi.seal.soprafs15.group_09_android.utils.GameStatus;

@AutoParcel @AutoGson
public abstract class Game implements Parcelable {

    // AutoParcel / AutoGson demand abstract dummy methods, getter/setter get autogenerated upon build.
    @Nullable
    public abstract Long id();
    @Nullable
    public abstract String name();
    @Nullable
    public abstract String token();
    @Nullable
    public abstract String owner();
    @Nullable
    public abstract GameStatus status();
    @Nullable
    public abstract Integer numberOfMoves();
    @Nullable
    public abstract Integer numberOfPlayers();
    @Nullable
    public abstract String currentPlayer();
    @Nullable
    public abstract String channelName();

    public static Game create( String name,
                               String token ) {
        return new AutoParcel_Game( null, name, token, null, null, null, null, null, null );
    }
}

