package ch.uzh.ifi.seal.soprafs15.group_09_android.models;

import android.os.Parcelable;

import auto.parcel.AutoParcel;
import ch.uzh.ifi.seal.soprafs15.group_09_android.models.gson.AutoGson;

@AutoParcel @AutoGson
public abstract class User implements Parcelable {

    // AutoParcel / AutoGson demand abstract dummy methods, getter/setter get autogenerated upon build.
    public abstract String username();
    public abstract Integer age();

    public static User create(String username, Integer age) {
        return new AutoParcel_User(username, age);
    }

}

